from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import text
from app.database import get_sync_db
from app.core.cache import get_cached_report, set_cached_report
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
import io

router = APIRouter()

PRIMARY    = colors.HexColor("#5C6BC0")
ACCENT     = colors.HexColor("#EF5350")
GOLD       = colors.HexColor("#FFA726")
TEAL       = colors.HexColor("#26A69A")
BG_DARK    = colors.HexColor("#1A1A2E")
ROW_EVEN   = colors.HexColor("#F5F5F5")
ROW_ODD    = colors.white
HEADER_BG  = colors.HexColor("#303F9F")


def build_pdf(data: dict, quarter: str, age_group: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=15*mm, bottomMargin=15*mm,
        title=f"FAERS Pediatric Report — {quarter or 'ALL'}",
    )
    styles = getSampleStyleSheet()
    story = []

    def h1(text):
        return Paragraph(f"<font color='#{PRIMARY.hexval()}' size=16><b>{text}</b></font>", styles["Heading1"])

    def h2(text):
        return Paragraph(f"<font color='#{TEAL.hexval()}' size=13><b>{text}</b></font>", styles["Heading2"])

    def body(text):
        return Paragraph(text, styles["BodyText"])

    # ── Cover ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 20*mm))
    story.append(h1("FAERS Pediatric ADR Analysis Report"))
    story.append(body("Generated by PulseTech Dashboard"))
    story.append(body(f"Quarter: {quarter or 'ALL'}  |  Age Group: {age_group or 'All Age Groups'}"))
    story.append(HRFlowable(width="100%", thickness=1, color=PRIMARY))
    story.append(Spacer(1, 8*mm))

    # ── Executive Summary ──────────────────────────────────────────────
    s = data.get("summary", {})
    story.append(h2("Executive Summary"))
    summary_rows = [
        ["Total Patients", "Confirmed Signals", "Suspect Drugs", "Unique ADRs", "Age Groups"],
        [
            f"{s.get('total_patients', 0):,}",
            f"{s.get('total_signals', 0):,}",
            f"{s.get('total_suspect_drugs', 0):,}",
            f"{s.get('total_adverse_reactions', 0):,}",
            str(len(s.get('age_distribution', {}))),
        ]
    ]
    summary_tbl = Table(summary_rows, colWidths=[36*mm]*5)
    summary_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, 0), 9),
        ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME",   (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 1), (-1, 1), 14),
        ("TEXTCOLOR",  (0, 1), (0, 1),  PRIMARY),
        ("TEXTCOLOR",  (1, 1), (1, 1),  ACCENT),
        ("TEXTCOLOR",  (2, 1), (2, 1),  TEAL),
        ("TEXTCOLOR",  (3, 1), (3, 1),  GOLD),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, 1), [ROW_EVEN]),
    ]))
    story.append(summary_tbl)
    story.append(Spacer(1, 8*mm))

    # ── Demographics ───────────────────────────────────────────────────
    story.append(h2("Demographics Overview"))
    
    # These are now dictionaries, e.g. {"CHILD": 123, "ADOLESCENT": 45}
    age_dist = data.get("summary", {}).get("age_distribution", {})
    if not age_dist:
        age_dist = data.get("age_distribution", {}) # fallback
        
    sex_dist = data.get("summary", {}).get("sex_distribution", {})
    if not sex_dist:
        sex_dist = data.get("sex_distribution", {}) # fallback

    age_rows  = [["Age Group", "Patient Count"]]
    for group, count in age_dist.items():
        age_rows.append([str(group), f"{count:,}"])

    sex_rows  = [["Sex", "Patient Count"]]
    for sex, count in sex_dist.items():
        sex_rows.append([str(sex), f"{count:,}"])

    age_tbl = Table(age_rows, colWidths=[50*mm, 40*mm])
    sex_tbl = Table(sex_rows, colWidths=[50*mm, 40*mm])

    def demo_style(tbl):
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ROW_ODD, ROW_EVEN]),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("TEXTCOLOR",  (1, 1), (1, -1), TEAL),
        ]))

    demo_style(age_tbl)
    demo_style(sex_tbl)

    demo_combined = Table([[age_tbl, sex_tbl]], colWidths=[95*mm, 95*mm])
    demo_combined.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
    story.append(demo_combined)
    story.append(Spacer(1, 8*mm))

    # ── Top 10 Drugs ────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(h2("Top 10 Suspect Drugs (Primary Suspect)"))
    drug_rows = [["#", "Drug Name", "Reports"]]
    for i, d in enumerate(data.get("top_suspect_drugs", data.get("top_drugs", []))[:10], 1):
        drug_rows.append([str(i), d.get("drug", ""), f"{d.get('count', 0):,}"])
    drug_tbl = Table(drug_rows, colWidths=[12*mm, 140*mm, 28*mm])
    drug_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ROW_ODD, ROW_EVEN]),
        ("TEXTCOLOR",  (2, 1), (2, -1), TEAL),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
    ]))
    story.append(drug_tbl)
    story.append(Spacer(1, 6*mm))

    # ── Top 10 ADRs ─────────────────────────────────────────────────────
    story.append(h2("Top 10 Adverse Reactions"))
    adr_rows = [["#", "ADR (PT Term)", "Reports"]]
    for i, r in enumerate(data.get("top_adverse_reactions", data.get("top_reactions", []))[:10], 1):
        adr_rows.append([str(i), r.get("adr", ""), f"{r.get('count', 0):,}"])
    adr_tbl = Table(adr_rows, colWidths=[12*mm, 140*mm, 28*mm])
    adr_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ROW_ODD, ROW_EVEN]),
        ("TEXTCOLOR",  (2, 1), (2, -1), ACCENT),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
    ]))
    story.append(adr_tbl)
    story.append(Spacer(1, 6*mm))

    # ── Outcome Distribution ────────────────────────────────────────────
    story.append(h2("Outcome Distribution"))
    out_rows = [["Outcome Code", "Count"]]
    outcomes_dict = data.get("outcomes", {})
    if isinstance(outcomes_dict, list):
        outcomes_dict = {o.get("outc_cod"): o.get("count") for o in outcomes_dict}
        
    for code, count in outcomes_dict.items():
        out_rows.append([str(code), f"{count:,}"])
    out_tbl = Table(out_rows, colWidths=[80*mm, 50*mm])
    out_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [ROW_ODD, ROW_EVEN]),
        ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTSIZE",   (0, 0), (-1, -1), 9),
    ]))
    story.append(out_tbl)

    # ── Signal Detection Results ──────────────
    story.append(PageBreak())
    story.append(h2("Signal Detection Results"))
    
    all_signals = data.get("top_signals", [])
    
    # Cap at 10,000 to ensure specific quarters (5k-8k signals) get fully exported, 
    # while "ALL Quarters" (82k+ signals) gets safely capped to prevent memory crashes.
    MAX_PDF_SIGNALS = 10000
    signals = all_signals[:MAX_PDF_SIGNALS]
    
    total_signals = s.get("total_signals", len(all_signals))
    
    if len(all_signals) > MAX_PDF_SIGNALS:
        story.append(body(
            f"Showing top {len(signals):,} confirmed signals "
            f"(out of {total_signals:,} total confirmed in dataset), "
            f"sorted by PRR descending. Limited to {MAX_PDF_SIGNALS:,} to ensure fast PDF generation."
        ))
    else:
        story.append(body(
            f"Showing all {len(signals):,} confirmed signals "
            f"(total confirmed in dataset: {total_signals:,}), "
            f"sorted by PRR descending."
        ))
        
    story.append(Spacer(1, 4*mm))

    sig_rows = [["#", "Drug", "ADR", "Age Group", "N11", "PRR", "ROR", "IC025", "EBGM"]]
    for i, sig in enumerate(signals, 1):
        sig_rows.append([
            str(i),
            (sig.get("drugname_normalized", sig.get("drug", "")) or "")[:30],
            (sig.get("pt_term", sig.get("adr", "")) or "")[:35],
            sig.get("age_group", ""),
            str(sig.get("n11", "")),
            f"{sig.get('prr', 0) or 0:.2f}",
            f"{sig.get('ror', 0) or 0:.2f}",
            f"{sig.get('ic025', 0) or 0:.2f}",
            f"{sig.get('ebgm', 0) or 0:.2f}",
        ])

    sig_tbl = Table(
        sig_rows,
        colWidths=[10*mm, 42*mm, 48*mm, 22*mm, 13*mm, 13*mm, 13*mm, 13*mm, 13*mm],
        repeatRows=1,  # header repeats on every new page automatically
    )
    sig_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 7),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [ROW_ODD, ROW_EVEN]),
        ("TEXTCOLOR",     (5, 1), (5, -1), ACCENT),
        ("GRID",          (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 3),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 3),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(sig_tbl)

    doc.build(story)
    return buf.getvalue()


@router.get("/export-pdf")
def export_pdf(
    quarter: str | None = Query(None),
    age_group: str | None = Query(None),
    db: Session = Depends(get_sync_db),
):
    # Get data (from in-memory cache or compute fresh)
    data = get_cached_report(quarter, age_group)
    if not data:
        result = db.execute(
            text("SELECT compute_faers_report(:quarter, :age_group)"),
            {"quarter": quarter, "age_group": age_group}
        ).scalar()
        data = dict(result)
        set_cached_report(quarter, age_group, data)

    q_label = quarter or "ALL"
    ag_label = (age_group or "all").replace(" ", "_")
    filename = f"FAERS_Pediatric_Report_{q_label}_{ag_label}.pdf"

    pdf_bytes = build_pdf(data, quarter or "ALL", age_group or "All Age Groups")

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
